_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_30shot_seed1',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (216000,)
  MAX_ITER: 240000
  CHECKPOINT_PERIOD: 12000
  WARMUP_ITERS: 10
OUTPUT_DIR: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_30shot"