_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "few-shot-object-detection/checkpoints/R-101.pkl"
  MASK_ON: False
  META_ARCHITECTURE: GeneralizedDecoupledRCNN
  GDL:
      rpn_scale: 0.0
      rcnn_scale: 0.75
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_trainval_base',)
  TEST: ('coco_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (85000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 25000
  BASE_LR: 0.02
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
OUTPUT_DIR: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base_grad"