_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: GeneralizedDecoupledRCNN
  WEIGHTS: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_reset_surgery.pth"
  GDL:
    rcnn_scale: 0.01
    rpn_scale: 0.0
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: False
  BACKBONE:
    FREEZE: False
  PROPOSAL_GENERATOR:
    FREEZE: False
DATASETS:
  TRAIN: ('coco_trainval_all_30shot_seed1',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (216000,)
  MAX_ITER: 240000
  CHECKPOINT_PERIOD: 60000
  WARMUP_ITERS: 100
OUTPUT_DIR: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_grad_30shot"