_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base/model_0104999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_trainval_base',)
  TEST: ('coco_test_base',)
SOLVER:
  IMS_PER_BATCH: 12
  STEPS: (85000, 100000)
  MAX_ITER: 110000
OUTPUT_DIR: "few-shot-object-detection/checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_base"