_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/vaipe/TFA_fastercnn_base_r50/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 231
  VISUALIZATION: True
DATASETS:
  TRAIN: ('vaipe_train_base',)
  TEST: ('vaipe_test_base',)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (10000, 20000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "checkpoints/vaipe/TFA_fastercnn_base_r50"