_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/aiotlab/projects/huyvinuni/RFC/few-shot-object-detection/checkpoints/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 246
DATASETS:
  TRAIN: ('emed_train_base',)
  TEST: ('emed_test_base',)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (10000, 20000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "/home/aiotlab/projects/huyvinuni/RFC/few-shot-object-detection/checkpoints/emed/faster_rcnn/faster_rcnn_R_50_FPN_base"
