_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/emed/faster_rcnn/faster_rcnn_R_50_FPN_base/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 267
    FREEZE_FEAT: False
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('emed_train_all_13shot_seed1',)
  TEST: ('emed_test_all',)
SOLVER:
  IMS_PER_BATCH: 9
  BASE_LR: 0.001
  STEPS: (10000,)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/home/aiotlab/projects/huyvinuni/RFC/few-shot-object-detection/checkpoints/emed/faster_rcnn_R_50_FPN_ft_fc_roi_all_13shot"