VERSION: 2
MODEL:
  META_ARCHITECTURE: "SparseRCNN"
  WEIGHTS: "checkpoints/emed/sparse_rcnn/sparse_rcnn_R_50_base/model_reset_surgery.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE: True
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
    STRIDE_IN_1X1: False
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 267
    INIT_PROP_FREEZE: True
    HEAD_FREEZE_EXCP6: False
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.000015
  STEPS: (10000, 15000)
  MAX_ITER: 18000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0  # keep same with BASE_LR.
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
SEED: 40244023
TRAINER: "SparseRCNN_Trainer"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
DATASETS:
  TRAIN: ('emed_train_all_13shot_seed1',)
  TEST: ('emed_test_all',)
OUTPUT_DIR: "checkpoints/emed/sparse_rcnn/sparse_rcnn_R_50_ft_head_withoutprop_13shot"