_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeometricRCNN"
  WEIGHTS: "checkpoints/vaipe/Geometric_fastercnn_base_r50_128/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 262
    FREEZE_GEOMETRIC: True
    NAME: "GeometricROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "GeometricConvFCHead"
    NUM_FC: 2
    NUM_CONV: 4
    CONV_DIM: 128
    EDGE_DIM: 64
    TEXTURE_DIM: 64 
    POOLER_RESOLUTION: 7
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('vaipe_train_all_13shot',)
  TEST: ('vaipe_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (20000,)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 1000
OUTPUT_DIR: "checkpoints/vaipe/Geometric_fastercnn_r50_ft_13shot_128"
