_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "LowRankRCNN"
  WEIGHTS: "checkpoints/vaipe/TFA_fastercnn_base_r50/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: LowRankROIHeads
    NUM_CLASSES: 262
    FREEZE_FEAT: False
  ROI_BOX_HEAD:
    WEIGHT_PATH: "checkpoints/vaipe/TFA_fastercnn_base_r50/fc1.pkl"
    NAME: "LowRankConvFCHead"
    NUM_FC: 3
    POOLER_RESOLUTION: 7
    RANK: 170
    RANK_UPDATE: 10
    FREEZE_LRT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('vaipe_train_all_13shot',)
  TEST: ('vaipe_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (10000,)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 1000
OUTPUT_DIR: "checkpoints/vaipe/faster_rcnn_R_50_FPN_ft_lowrank20_3layernorm_13shot"